export const GET_ERRORS = "GET_ERRORS";
export const GET_ALPHABETS = "GET_ALPHABETS";
export const GET_ALPHABETS1 = "GET_ALPHABETS1";

export const UPDATE_TO_ZERO = "UPDATE_TO_ZERO";
export const UPDATE_TO_ONE = "UPDATE_TO_ONE";
export const UPDATE_ALL_ZERO = "UPDATE_ALL_ZERO";
export const UPDATE_ALL_ONE = "UPDATE_ALL_ONE";
